### ISSUE TITLE
PARAM_INVALID

### ISSUE THREAD

**Issue by VigersRay** [David-Lor/python-qqddm#10]
{"code":-2100, "msg":"PARAM_INVALID"}
Maybe problem in extra parameters.

**Comment by David-Lor** [comment]
AFAIK that error means "Possibly invalid file or image format (gif, webp and other uncommon formats seem to be unsupported)". Here I've documented all errors I know about: https://github.com/David-Lor/python-qqddm/blob/develop/docs/qqddm-api.md#c2i-identified-errors

I forget about creating a custom exception for that particular error though, will do in the future.

**Comment by VigersRay** [comment]
This error is thrown on all files, including those used in example.py. I could solve the problem through the browser's devtools, but the site does not want to work even with a Chinese IP

**Comment by David-Lor** [comment]
It's working fine for me at this moment, using a chinese public proxy and uploading `docs/group1-pic1.png`:

![image](https://user-images.githubusercontent.com/17401854/206524864-90b6b699-4cee-4e87-a7d0-1a469f7a8516.png)

**Comment by David-Lor** [comment]
(I keep the issue opened until I add a custom exception for this error)

**Comment by VigersRay** [comment]
> В данный момент у меня все работает нормально, используя китайский общедоступный прокси и загружая `docs/group1-pic1.png`:
> 
> ![изображение](https://user-images.githubusercontent.com/17401854/206524864-90b6b699-4cee-4e87-a7d0-1a469f7a8516.png)


It worked for me too
