### ISSUE TITLE
Setting Up Chinese proxy

### ISSUE THREAD

**Issue by 20kzhan** [David-Lor/python-qqddm#12]
What would I set my environment variable to in order to get a chinese proxy? Running it straight from my command prompt gives: `API returned error (The current country is blocked by the API); response body: {"code":2119, "msg":"user_ip_country 美国"}`

Which is expected, but there's nothing in the example about how to set up a proxy. So what would I set my "PROXY" environment variable to?
<img width="274" alt="image" src="https://user-images.githubusercontent.com/49377371/206877282-f92e5ec7-1225-40e7-9b95-a51c75e0ba19.png">

**Comment by David-Lor** [comment]
On Linux you can do the following for setting the environment variable when running the example script:

```bash
PROXY="socks5://ip:host" python example.py
```

supposing the proxy is a socks5 proxy, otherwise change the protocol to socks4, https or whatever
