### ISSUE TITLE
The current country is blocked by the API

### ISSUE THREAD

**Issue by Ruddy35** [David-Lor/python-qqddm#15]
Hello. I i install version 0.1.1 and dont use proxy. In proccess library return error "The current country is blocked by the API".

And i have another question. How to open web app. I use china proxy but when i click button on website nothing happen. In console i see error 
Failed to launch 'mqqapi://...' because the scheme does not have a registered handler.

**Comment by David-Lor** [comment]
> Hello. I i install version 0.1.1 and dont use proxy. In proccess library return error "The current country is blocked by the API".

It's currently working from here, which country are you running the requests from?

> And i have another question. How to open web app. I use china proxy but when i click button on website nothing happen. In console i see error Failed to launch 'mqqapi://...' because the scheme does not have a registered handler.

I had the same problem in some cases, I'm not sure but it may happen when you're behind a proxy (in my case sometimes I go to the web app through Tor and maybe in these cases I had that problem). Maybe try changing browser or using no proxy
