### ISSUE TITLE
Help with proxy

### ISSUE THREAD

**Issue by SuperZombi** [David-Lor/python-qqddm#16]
Can you recommend some free proxy or free hosting server for python?
I'm using [REPL](https://replit.com/) and theirs servers located at US, so this library not working ("service upgrade" error). I was tried many proxies, but no one don't suit ((

**Comment by David-Lor** [comment]
@SuperZombi Are you using latest version? Theorically it's working again from outside China, although I don't know if it works from US.

When they limited to China, I was able to use certain chinese proxies from [here](http://free-proxy.cz/en/proxylist/country/CN/socks5/ping/all). You may also try using Tor (I haven't tried it yet at the current API state) - my personal preference is using [this Docker image](https://github.com/rdsubhas/docker-tor-privoxy-alpine).

**Comment by SuperZombi** [comment]
Yes, the latest ver. It works from Ukraine, but don't work from US.

**Comment by David-Lor** [comment]
I see. So maybe you can get it working using multiple Tor-to-socks proxy servers, or [proxybroker2](https://github.com/bluet/proxybroker2), if you don't want to manually search for working proxies.
