### ISSUE TITLE
"AUTH_FAILED" error

### ISSUE THREAD

**Issue by Hydra0071a** [David-Lor/python-qqddm#5]
they add an authorization header,
but someone managed to bypass it with js
[qq-neural-anime-tg](https://github.com/lmcsu/qq-neural-anime-tg)

**Comment by David-Lor** [comment]
Hi, I've tried the bot from that GitHub repository and it seems it's also getting the `AUTH_FAILED` error. I'd say this is just because the service seems to be under maintenance:

![image](https://user-images.githubusercontent.com/17401854/206037502-ae360640-daaf-497a-9809-834c6a42b82d.png)

**Comment by David-Lor** [comment]
I see, yesterday the bot was returning a response caused by the `AUTH_FAILED`, today seems to be working indeed. Did you get the `user_ip_country` error when using `python-qqddm` or other way?

**Comment by Hydra0071a** [comment]
Yes, but it was before they added the `AUTH_FAILED` response, It seems you can't use the AI if you are not from China unless you use proxies

**Comment by David-Lor** [comment]
> Yes, but it was before they added the `AUTH_FAILED` response, It seems you can't use the AI if you are not from China unless you use proxies

Alright, I've been playing around with the headers and found a way to make it work again, using chinese proxies indeed. Also sadly the API does not allow pictures without human faces no more (no cat pics :crying_cat_face: )
